version: "3.8"

services:
  http:
    build: ./http
    container_name: web
    volumes:
      - "./http/content:/var/www/html:ro"
      - "./http/conf/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./http/log:/var/log/nginx"
    ports:
      - target: 80
        published: 8080
  dhcp:
    build: ./dhcp
    container_name: dhcp
    volumes:
      - "./dhcp/data/dhcpd.conf:/data/dhcpd.conf:ro"
      - "./dhcp/data/dhcpd.leases:/data/dhcpd.leases"
    network_mode: host